### ISSUE TITLE
ラズパイ2B jessie V2カメラでANZUのダッシュボードからmomo確認できませんでした

### ISSUE THREAD

**Issue by qpcrazy** [shiguredo/momo-help#5]
すみません
教えていただけると助かります
以下の環境で動作させていますが、Momo映像確認ができない状態です
機器：ラズパイ２ B
OS ：Jessie
カメラ : V2カメラ

P2Pでは画面確認できるのですが、AnzuのダッシュボードにてMomoの映像確認ができない状況です
connect start :wss://anzu.shiguredo.jp/signaling
executeLauncher run
watchdogLauncher run
[2018-02-23 17:56:07] [connect] Successful connection
on_socket_init
[2018-02-23 17:56:07] [connect] WebSocket Connection 45.76.196.108:443 v-2 "WebSocket++/0.6.0" /signaling 101
on_open
send_message requestOffer:{"type":"connect","role":"upstream","channelId":"チャネルID","accessToken":"配信用トークン"}
on_close
[2018-02-23 17:56:07] [disconnect] Disconnect close local:[4490,UNKNOWN-TYPE] remote:[4490,UNKNOWN-TYPE]
reconnecting...

なにが原因かわからない状況のため、糸口だけでもご指摘いただけるとありがたいです
よろしくお願いいたします

**Comment by voluntas** [comment]
@qpcrazy Anzu のログを確認したところ、Anzu 側でも正常に接続できていないようで ChannelId が定義されていないというエラーが出ておりました。

Momo のバージョンは 1.0.0 を利用されておりますでしょうか？

**Comment by qpcrazy** [comment]
ありがとうございます

Momoのバージョンは、0.1.1
momo-gw_0.1.1_arm7.tar.gz　を使用しています

**Comment by voluntas** [comment]
@qpcrazy クイックスタートが古くて申し訳ありません。

- https://github.com/shiguredo/momo-help/releases/download/1.0.0/momo-gw_1.0.0_raspi2_arm7.deb
- https://github.com/shiguredo/momo-help/releases/download/1.0.0/momo-gw_1.0.0_arm7.tar.gz

1.0.0 がリリースされておりますので、上記のどちらかで再度お試しいただけますか？

**Comment by qpcrazy** [comment]
@voluntas 返事が遅く申し訳ありません
1.0.0でトライをしてみます
ありがとうございます

**Comment by qpcrazy** [comment]
@voluntas Ver.1.0.0を導入し動作を確認いたしました
ver1.0.0導入後
・同一ネットワーク内、index.htmlを使用しp2pでの画像確認できなかった（映像がでない）
・チャンネルID、配信用トークンを使用し、AnzuダッシュボードからMomo映像確認
　　→同一ネットワーク内のPCから映像確認できた
　　→外部ネットワーク下のケータイから映像確認できない（safari、chrome）
映像確認できない条件のものがいくつかあります

**Comment by voluntas** [comment]
@qpcrazy 確認できたとのことで了解しました。

>> ・同一ネットワーク内、index.htmlを使用しp2pでの画像確認できなかった（映像がでない）
P2P での接続は完全にネットワーク環境依存です。こちらは検証に利用したネットワーク側での対応をお勧めします。

>> ・チャンネルID、配信用トークンを使用し、AnzuダッシュボードからMomo映像確認
>> 　　→同一ネットワーク内のPCから映像確認できた
PC の OS が Windows / macOS / Linux のどれで、どのブラウザかに依存します。
macOS の Safari や Windows の Edge では動作はしません。

このあたりは momo ではなく、 WebRTC の知識になりますので、
手前味噌ではありますが以下をご覧いただければと思います。

WebRTC コトハジメ
https://gist.github.com/voluntas/67e5a26915751226fdcf

WebRTC の未来
https://gist.github.com/voluntas/59a135343538c290e515

>> 　　→外部ネットワーク下のケータイから映像確認できない（safari、chrome）
ケータイというのが iOS なのか Android なのかによりますが、
iOS の Safari では H.264 のみの対応となっているため、
VP8 でしか配信できない momo は見ることはできません。

また iOS の Chrome はベースがモバイル Safari となっており、
さらに現時点では WebRTC に対応しておりません。

詳細は上記の記事をご覧いただければと思います。

**Comment by qpcrazy** [comment]
@voluntas 大変丁寧にご対応いただきありがとうございました
教えていただきました2つの資料で勉強します

重ねてお礼申し上げます
ありがとうございました
